name: ruche_connectee
description: Application mobile pour la surveillance de ruches connectées

# Version du projet
version: 1.0.0+1

# Version minimale de Flutter
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dépendances
dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.7.20
  
  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  fl_chart: ^0.63.0
  shimmer: ^3.0.0
  
  # État et navigation
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^10.1.2
  
  # Utilitaires
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  connectivity_plus: ^4.0.2
  logger: ^2.0.1
  uuid: ^3.0.7
  
  # Injection de dépendances
  get_it: ^7.6.0
  injectable: ^2.3.0

# Dépendances de développement
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

# Configuration de Flutter
flutter:
  uses-material-design: true
  
  # Assets temporairement désactivés pour le développement
  # assets:
  #   - assets/images/
  #   - assets/icons/
    
  # Polices temporairement désactivées
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700