name: ruche_connectee
description: Application mobile pour la surveillance de ruches connectées

# Version du projet
version: 1.0.0+1

# Version minimale de Flutter
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dépendances
dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  
  # HTTP Client pour API REST
  http: ^1.1.0
  dio: ^5.4.3
  
  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^6.3.0
  fl_chart: ^0.69.0
  shimmer: ^3.0.0
  
  # État et navigation
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  go_router: ^14.2.7
  
  # Utilitaires
  intl: ^0.19.0
  shared_preferences: ^2.2.1
  connectivity_plus: ^6.1.5
  logger: ^2.0.2
  uuid: ^4.5.1
  
  # Injection de dépendances
  get_it: ^7.7.0
  injectable: ^2.1.2

# Dépendances de développement
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  mockito: ^5.4.2
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.2

# Configuration de Flutter
flutter:
  uses-material-design: true
  
  # Assets temporairement désactivés pour le développement
  # assets:
  #   - assets/images/
  #   - assets/icons/
    
  # Polices temporairement désactivées
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700