name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.x'
        cache: true
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Get dependencies
      run: flutter pub get
      working-directory: ruche-connectee/mobile-app
      
    - name: Build Android APK
      run: flutter build apk --release
      working-directory: ruche-connectee/mobile-app
      
    - name: Build Android App Bundle
      run: flutter build appbundle --release
      working-directory: ruche-connectee/mobile-app
      
    - name: Build Web
      run: flutter build web --release
      working-directory: ruche-connectee/mobile-app
      
    - name: Create Release Assets
      run: |
        cd ruche-connectee/mobile-app
        cp build/app/outputs/flutter-apk/app-release.apk ../../beetrack-mobile.apk
        cp build/app/outputs/bundle/release/app-release.aab ../../beetrack-mobile.aab
        cd build/web && tar -czf ../../../beetrack-web.tar.gz . && cd ../../..
        
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          beetrack-mobile.apk
          beetrack-mobile.aab
          beetrack-web.tar.gz
        generate_release_notes: true 